---
- name: 'Configure WIFI'
  copy: src=secret_files/wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600

#- name: 'Update APT package cache'
#  action: apt update_cache=yes

#- name: 'Upgrade APT to the latest packages'
#  action: apt upgrade=safe

- name: 'Ensure log directory'
  action: file dest={{log_dir}} state=directory mode=777

- name: 'Ensure data directory'
  action: file dest={{data_dir}} state=directory mode=770

- name: 'ensure .ssh directory'
  action: file dest=/root/.ssh/ state=directory mode=770

- name: 'copy over ssh keys for deploy purposes'
  action: copy src={{item.from}} dest={{item.to}} mode={{item.mode}}
  with_items:
      - { from: 'secret_files/deploy_rsa.pub', to: '/root/.ssh/id_rsa.pub', mode: '0644' }
      - { from: 'secret_files/deploy_rsa', to: '/root/.ssh/id_rsa', mode: '0600' }

- name: 'Deploy code from git'
  git: repo={{repo_url}} dest={{src_dir}} remote={{repo_remote}} version={{repo_branch}} accept_hostkey=yes force=yes
  tags: code

- name: copy files from reddeadnettle to /srv/www on remote host
  command: cp -r {{src_dir}}/reddeadnettle/. /srv/www
  tags: code

- name: 'Deploy oasisvr.info from git'
  git: repo=git@github.com:mhfowler/oasis-vr.git dest=/srv/www/oasisvr.info remote=origin version=master accept_hostkey=yes force=yes
  tags: code

- name: Install nginx site for specified site
  template:
    src: templates/localhost
    dest: /etc/nginx/sites-enabled/localhost

- name: Install nginx site for specified site
  template:
    src: templates/reddeadnettle.network
    dest: /etc/nginx/sites-enabled/reddeadnettle.network
  tags: code

- name: Install nginx site for specified site
  template:
    src: templates/oasisvr.info
    dest: /etc/nginx/sites-enabled/oasisvr.info
  tags: code

- name: Install nginx site for specified site
  template:
    src: templates/blog.sarisarisalon.org
    dest: /etc/nginx/sites-enabled/blog.sarisarisalon.org
  tags: code

- name: Install nginx site for specified site
  template:
    src: templates/localhost
    dest: /etc/nginx/sites-enabled/localhost
  tags: code


- name: Install nginx site for specified site
  template:
    src: templates/myfreehoroscope.today
    dest: /etc/nginx/sites-enabled/myfreehoroscope.today

- name: Install nginx site for specified site
  template:
    src: templates/test.reddeadnettle.network
    dest: /etc/nginx/sites-enabled/test.reddeadnettle.network
  tags: code


- name: 'Build python dependencies'
  apt:
    pkg:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev

- name: 'install python requirements'
  action: pip requirements={{src_dir}}/requirements.txt state=present executable=/usr/bin/pip3

- name: 'Copy secret.json file'
  copy: src=secret_files/secret.json dest={{src_dir}}/ansible-pi/secret_files/secret.json
  tags: code

- name: 'Copy luks-keyfile'
  copy: src=secret_files/luks-keyfile dest={{src_dir}}/ansible-pi/secret_files/luks-keyfile
  tags: code


- name: 'Copy rc.local'
  action: template src=templates/rc.local dest=/etc/rc.local
  tags: debug

- name: 'Copy etc/network/intefaces'
  action: template src=templates/interfaces dest=/etc/network/interfaces

- name: 'Copy cmdline.txt'
  action: template src=templates/cmdline.txt dest=/boot/cmdline.txt

- name: 'Copy motd'
  action: template src=templates/motd dest=/etc/motd

- name: 'install node'
  apt:
    pkg:
    - node
    - npm
  tags: debug

# https://www.npmjs.com/package/ngrok
- name: Install packages based on package.json.
  npm: path={{src_dir}}


# install ytalk
- name: 'install ytalk'
  apt:
    pkg:
    - ytalk

  # copy over /etc/profile
- name: 'Copy profile'
  action: template src=templates/profile dest=/etc/profile
  tags: code

# copy over /home/pi/.bash_profile
- name: 'Copy .bash_profile'
  action: template src=templates/.bash_profile dest={{bash_profile}}
  tags: code

- name: 'Copy .guide_prompt'
  action: template src=templates/guide_prompt.txt dest=/home/swim/.guide_prompt.txt
  tags: code

- name: 'Copy .guide'
  action: template src=templates/guide.txt dest=/home/swim/.guide.txt
  tags: code

- name: 'Copy commands'
  action: template src=templates/commands.txt dest=/home/swim/.commands.txt
  tags: code

- name: 'Ensure cron directory'
  action: file dest={{cron_dir}} state=directory mode=770

- name: Copy over cron jobs
  template:
    src: '{{ item.src }}'
    dest: '{{ cron_dir }}/{{ item.path }}'
  with_filetree: 'templates/cron'
  when: item.state == 'file'
  tags: code

- name: for dynamic dns cronjob
  cron:
    name: "dynamic dns"
    minute: "*/2"
    hour: "*"
    job: "{{cron_dir}}/dynamicdns.sh"
  tags: code

- name: for reboot util
  cron:
    name: "reboot util"
    minute: "*/5"
    hour: "*"
    job: "{{cron_dir}}/reboot_util.sh"
  tags: code

- name: for health check
  cron:
    name: "health check"
    minute: "*"
    hour: "*/10"
    user: "pi"
    job: "{{cron_dir}}/healthcheck.sh"
  tags: code

- name: for greetingroom cron job
  cron:
    name: "greetingroom"
    minute: "*"
    hour: "*"
    job: "{{cron_dir}}/greetingroom.sh"
  tags: code

- name: 'make /srv owned by admin'
  file: path=/srv state=directory owner=root group=admin recurse=yes
  tags: code

- name: 'set permissions for /srv'
  file:
    path: /srv
    state: directory
    mode: u=rwX,g=rX,o=
    owner: root
    group: admin
    recurse: yes
  tags: code

- name: 'set  permissions for /srv'
  command: chmod 770 /srv
  tags: code

- name: 'set  permissions for /srv/www/ssh.txt'
  command: chmod 660 /srv/www/ssh.txt
  tags: code

- name: 'set permissions for /greetingroom'
  file:
    path: /home/swim/greetingroom
    state: directory
    mode: u=rwX,g=rX,o=
    owner: swim
    group: swim
    recurse: yes
  tags: code

- name: set  permissions for .readme and .runme
  command: find /home/swim/greetingroom -type f -name \*.runme
  tags: code

- name: 'make bash scripts executable'
  file: path={{src_dir}}/bash state=directory mode=770 owner=root group=admin recurse=yes
  tags: code

- name: 'make cron jobs executable'
  file: path={{cron_dir}} state=directory mode=770 owner=root group=admin recurse=yes
  tags: code


#- name: 'Reboot'
#  command: /sbin/reboot

