---
#- name: 'crontab to add new users'
#  cron: name="add new users" minute="*/1" job="export PYTHONPATH={{src_dir}}:$PYTHONPATH && /usr/bin/python {{src_dir}}/oasis_python/create_new_users.py > {{log_dir}}/cron.log 2> {{log_dir}}/cron.error"
#  tags: cron

#- name: for removing add new users cronjob
#  cron: name="add new users" state=absent
#  tags: code

- name: 'install imageviewers'
  action: apt pkg=$item state=installed
  with_items:
    - imagemagick
    - caca-utils

# https://www.npmjs.com/package/ngrok
- name: Install packages based on package.json.
  npm: path={{src_dir}}

# install ytalk
- name: 'install ytalk'
  action: apt pkg=$item state=installed
  with_items:
    - ytalk

- name: 'crontab for greeting room'
  cron: name="greeting room" minute="*/1" job="{{src_dir}}/bash/greetingroom.sh"
  tags: cron

- name: 'make bash scripts executable'
  file: path={{src_dir}}/bash state=directory mode=0770 owner=root group=root recurse=yes
  tags: code

- name: 'make gallery scripts executable by oasis group'
  file: path={{src_dir}}/pi_utilities/gallery state=directory mode=0770 owner=root group=oasis recurse=yes
  tags: code